language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      script:
        - cargo build --all-features

    - rust: 1.20.0
    - rust: 1.26.0
    - rust: 1.36.0

script:
  - cargo build
  - cargo build --release
  - cargo build --no-default-features
  - cargo build --no-default-features --features std
  - cargo build --no-default-features --features alloc
  - cargo test --features "serde colls_traits"
