language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: nightly
      script:
        - cargo update -Z minimal-versions
        - cargo build --all-features

        - cargo update
        - cargo build --all-features

    - rust: 1.20.0
    - rust: 1.22.0
    - rust: 1.26.0
    - rust: 1.29.0
    - rust: 1.34.0
    - rust: 1.36.0

script:
  - cargo build
  - cargo build --no-default-features
  - cargo build --no-default-features --features alloc
  - cargo build --no-default-features --features std
  - cargo test --features "colltraits"
  - cargo test --features "serde"
  - cargo test --features "serde colltraits"
