language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.20.0
    - rust: 1.26.0

script:
  - cd "${TRAVIS_BUILD_DIR}/core_extensions"
  - cargo build
  - cargo build --no-default-features
  - cargo test
  - cargo build
