language: rust

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
    - rust: 1.20.0
    - rust: 1.26.0

script:
  - cargo build
  - cargo build --release
  - cargo build --no-default-features
  - cargo test
