cargo test --no-default-features --features "std bools"
cargo test --no-default-features --features "std callable"
cargo test --no-default-features --features "std collections"
cargo test --no-default-features --features "std const_default"
cargo test --no-default-features --features "std const_val"
cargo test --no-default-features --features "std integers"
cargo test --no-default-features --features "std iterators"
cargo test --no-default-features --features "std marker_type"
cargo test --no-default-features --features "std on_drop"
cargo test --no-default-features --features "std option_result"
cargo test --no-default-features --features "std phantom"
cargo test --no-default-features --features "std self_ops"
cargo test --no-default-features --features "std slices"
cargo test --no-default-features --features "std strings"
cargo test --no-default-features --features "std transparent_newtype"
cargo test --no-default-features --features "std type_asserts"
cargo test --no-default-features --features "std type_identity"
cargo test --no-default-features --features "std type_level_bool"
cargo test --no-default-features --features "std void"

cargo test --no-default-features --features "all_items"
cargo test --no-default-features --features "alloc all_items"
cargo test --no-default-features --features "std all_items"